package com.fittribe.api.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA mapping for the {@code user_progress_snapshot} table (Flyway V35).
 *
 * <p>One row per user — UUID primary key with no surrogate id. The
 * {@code data} column is opaque JSONB owned by
 * {@code ProgressSnapshotService}; schema evolution is tracked via
 * {@code schema_version} without requiring a DDL migration.
 *
 * <p>There is no {@code @GeneratedValue} because {@code user_id} is
 * supplied by the caller (copied from {@code users.id}) rather than
 * generated by the database.
 *
 * <h3>Write path</h3>
 * Always use
 * {@link com.fittribe.api.repository.UserProgressSnapshotRepository#upsert}
 * — JPA {@code save()} would attempt an INSERT even when the row
 * already exists, which would violate the PK constraint. The native
 * {@code ON CONFLICT (user_id) DO UPDATE} handles both first-write and
 * recompute in one round trip.
 */
@Entity
@Table(name = "user_progress_snapshot")
public class UserProgressSnapshot {

    @Id
    @Column(name = "user_id", updatable = false, nullable = false)
    private UUID userId;

    /**
     * Latest computed progress payload serialised as JSON.
     * Shape is owned by {@code ProgressSnapshotService}; bump
     * {@code schema_version} when the structure changes incompatibly.
     */
    @Column(name = "data", nullable = false, columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private String data = "{}";

    /** Tracks the Java-side {@code data} payload shape. Increment on incompatible changes. */
    @Column(name = "schema_version", nullable = false)
    private Integer schemaVersion = 1;

    /** Set by the database on insert and updated by the upsert query. Not writable from JPA. */
    @Column(name = "computed_at", insertable = false, updatable = false)
    private Instant computedAt;

    public UserProgressSnapshot() {}

    // ── Accessors ─────────────────────────────────────────────────────────

    public UUID getUserId() { return userId; }
    public void setUserId(UUID userId) { this.userId = userId; }

    public String getData() { return data; }
    public void setData(String data) { this.data = data; }

    public Integer getSchemaVersion() { return schemaVersion; }
    public void setSchemaVersion(Integer schemaVersion) { this.schemaVersion = schemaVersion; }

    public Instant getComputedAt() { return computedAt; }
}
